# Generated by Django 5.2.9 on 2026-04-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farm_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
